In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

import re
import os
import math

print('Libraries imported!')

Libraries imported!


## 1. Project Configuration


| Constant | Purpose |
|---|---|
| `BASE_DIR` | Root of the project (notebook's working directory) |
| `RAW_DIR` | `BASE_DIR/data/raw` — raw OHLCV CSVs |
| `PROCESSED_DIR` | `BASE_DIR/data/processed` — feature-engineered CSVs |

In [22]:
BASE_DIR      = Path("/home/rishabhmeel/DAI_project")
RAW_DIR       = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

print('RAW_DIR      :', RAW_DIR)
print('PROCESSED_DIR:', PROCESSED_DIR)

RAW_DIR      : /home/rishabhmeel/DAI_project/data/raw
PROCESSED_DIR: /home/rishabhmeel/DAI_project/data/processed

# 2. Loading the data

In [23]:
df = pd.read_excel(os.path.join(RAW_DIR,'datasheet.xls'))
df
# for col in df.columns:
#     print(repr(col))

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.01,22.98,973.31,927.41,98.01,...,32.86,11.06,46.97,13.35,13.16,5.37,63.46,76.79,29.59,64.49
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.66,19.82,949.82,844.43,100.00,...,22.62,5.97,32.20,1.70,0.25,15.84,46.77,70.47,5.08,45.26
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.68,20.95,967.48,934.92,96.53,...,17.88,6.09,26.90,1.32,0.67,8.00,19.60,50.76,1.72,32.81
3,Srikakulam,Andhra Pradesh,874,780,100,59.99,20.71,1139.51,1162.58,94.96,...,14.37,5.51,22.89,1.04,0.23,3.76,7.09,21.32,0.55,28.26
4,Vizianagaram,Andhra Pradesh,902,853,134,55.95,20.56,1114.35,898.03,95.42,...,14.83,6.43,25.13,4.90,0.63,7.33,11.41,21.47,0.80,32.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,South Twenty Four Pargana,West Bengal,917,1089,148,80.93,25.49,1054.81,1099.04,97.56,...,13.03,4.28,19.13,0.00,0.00,0.20,6.28,49.76,0.39,16.54
703,Paschim Medinipur,West Bengal,910,1002,137,72.10,23.43,1088.57,1005.04,99.32,...,10.66,4.33,18.98,0.00,0.00,0.00,18.83,50.48,1.46,20.81
704,Purba Medinipur,West Bengal,873,957,131,83.04,23.85,1031.40,777.38,99.25,...,11.92,4.40,21.31,0.00,0.19,0.46,12.93,40.11,1.97,14.80
705,Paschim Barddhaman,West Bengal,912,1190,184,74.84,22.32,977.46,786.93,97.70,...,14.45,3.67,20.67,0.70,1.30,0.40,11.79,40.23,0.83,14.58
706,Purba Barddhaman,West Bengal,915,1088,163,71.15,22.21,1067.12,877.10,99.61,...,11.50,3.82,18.39,0.19,0.10,0.00,9.93,50.06,1.17,22.94

# 3. Choosing the particular columns

In [24]:
cols_to_keep = [
    "District Names",
    "State/UT",
    "Children under 5 years who are stunted (height-for-age)18 (%)",
    "Children under 5 years who are wasted (weight-for-height)18 (%)",
    "Children under 5 years who are underweight (weight-for-age)18 (%)",
    "Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)",
    "Households with any usual member covered under a health insurance/financing scheme (%)",
    "Women (age 15-49) who are literate4 (%)",
    "Women (age 15-49)  with 10 or more years of schooling (%)",
    "Population living in households that use an improved sanitation facility2 (%)",
    "Population living in households with an improved drinking-water source1 (%)",
    "Population living in households with electricity (%)",
    "Households using clean fuel for cooking3 (%)",
    "Total children age 6-23 months receiving an adequate diet16, 17  (%)",
    "Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)",
    "Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)",
    "Children under age 5 years whose birth was registered with the civil authority (%)"
]

df = df[cols_to_keep].copy()
display(df)

,District Names,State/UT,Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%),Households with any usual member covered under a health insurance/financing scheme (%),Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Population living in households that use an improved sanitation facility2 (%),Population living in households with an improved drinking-water source1 (%),Population living in households with electricity (%),Households using clean fuel for cooking3 (%),"Total children age 6-23 months receiving an adequate diet16, 17 (%)",Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Mothers who had at least 4 antenatal care visits (for last birth in the 5 years before the survey) (%),Children under age 5 years whose birth was registered with the civil authority (%)
0,Nicobars,Andaman & Nicobar Islands,21.59,15.69,24.60,-64.21,2.65,87.54,53.53,83.45,98.81,97.90,56.93,-18.71,37.67,71.65,98.01
1,North & Middle Andaman,Andaman & Nicobar Islands,27.02,26.97,42.80,*,2.07,84.01,41.03,86.38,92.20,93.24,61.25,-5.92,30.38,79.19,100.00
2,South Andaman,Andaman & Nicobar Islands,21.11,12.62,17.43,-76.29,1.15,86.67,57.50,89.33,97.94,99.58,91.92,23.49,43.35,85.94,96.53
3,Srikakulam,Andhra Pradesh,19.66,19.51,21.44,-82.79,75.63,64.32,42.51,71.58,87.73,99.91,74.70,16.14,59.61,78.41,94.96
4,Vizianagaram,Andhra Pradesh,36.40,19.23,32.21,-76.75,76.69,58.32,37.63,61.74,93.10,99.52,60.30,1.75,66.74,71.35,95.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,South Twenty Four Pargana,West Bengal,36.70,21.21,32.15,91.66,36.72,85.59,34.94,70.08,100.00,99.24,36.19,27.55,70.42,87.50,97.56
703,Paschim Medinipur,West Bengal,31.07,30.27,39.99,76.93,25.75,70.85,26.19,58.33,95.53,95.41,17.46,21.78,65.98,63.09,99.32
704,Purba Medinipur,West Bengal,25.77,15.53,30.59,88.37,21.53,77.00,30.87,69.78,87.79,98.97,17.01,20.93,67.47,56.81,99.25
705,Paschim Barddhaman,West Bengal,39.74,25.45,40.96,62.4,21.82,73.45,37.12,71.46,95.21,97.00,56.29,31.05,74.69,70.41,97.70
706,Purba Barddhaman,West Bengal,32.67,21.10,31.63,97.2,37.18,73.19,27.32,64.15,99.13,96.76,32.05,34.1,71.52,80.50,99.61

# 4. Adding the MPI with the main data